#!/usr/bin/env python
# coding: utf-8

colors = {
    'black' : 'svartur',
    'blue' : 'blár',
    'brown' : 'brúnn',
    'green' : 'grænn',
    'gray' : 'grár',
    'orange' : 'appelsínugulur',
    'pink' : 'bleikur',
    'purple' : 'fjólublár',
    'red' : 'rauður',
    'white' : 'hvítur',
    'yellow' : 'gulur'
}

numbers = {
    '1' : 'einn',
    '2' : 'tveir',
    '3' : 'þrír',
    '4' : 'fjórir',
    '5' : 'fimm',
    '6' : 'sex',
    '7' : 'sjö',
    '8' : 'átta',
    '9' : 'níu',
    '10' : 'tíu',
    '11' : 'ellefu',
    '12' : 'tólf',
    # '13' : 'þrettán',
    # '14' : 'fjórtán',
    # '15' : 'fimmtán',
    # '16' : 'sextán',
    # '17' : 'sautján',
    # '18' : 'átján',
    # '19' : 'nítján',
    # '20' : 'tuttugu',
    # '21' : 'tuttugu og einn',
    # '22' : 'tuttugu og tveir',
    # '23' : 'tuttugu og þrír',
    # '30' : 'þrjátíu',
    # '31' : 'þrjátíu og einn',
    # '40' : 'fjörutíu',
    # '50' : 'fimmtíu',
    # '60' : 'sextíu',
    # '70' : 'sjötíu',
    # '80' : 'áttatíu',
    # '90' : 'níutíu',
    # '100': 'hundrað',
    '101': 'hundrað og einn',
    '200': 'tvö hundruð'
}

body_parts =  {
    'arm' : 'armur',
    'back' : 'hryggur',
    'belly button' : 'nafli',
    'blood' : 'blóð',
    'cheek' : 'kinn',
    'chest (for a man)' : 'brjóstkassi',
    'chest/breast (for a woman)' : 'brjóst',
    'chin' : 'haka',
    # 'ear' : 'eyra',
    # 'elbow' : 'olnbogi',
    # 'eye' : 'auga',
    # 'finger' : 'fingur',
    # 'foot' : 'fótur',
    # 'forehead' : 'enni',
    # 'hair' : 'hár',
    # 'hand' : 'hönd',
    # 'head' : 'höfuð',
    # 'heart' : 'hjarta',
    # 'heel' : 'hæll',
    # 'hip' : 'mjöðm',
    # 'index finger' : 'vísifingur',
    # 'knee' : 'kné',
    # 'larynx' : 'barkakýli',
    # 'leg' : 'fótur',
    # 'lip' : 'vör',
    # 'middle finger' : 'löngutöng',
    # 'mouth' : 'munnur',
    # 'muscle' : 'vöðvi',
    # 'mustache' : 'grön',
    # 'nail' : 'nögl',
    # 'neck' : 'háls',
    # 'nose' : 'nef',
    # 'pinkie' : 'litilfingur',
    # 'rib' : 'la costola',
    # 'ring finger' : 'hringfingur',
    # 'shoulder' : 'öxl',
    # 'skeleton' : 'beinagrind',
    'stomach' : 'maga',
    'teeth' : 'tönn',
    'thigh' : 'læri',
    'thumb' : 'þumall',
    'vein' : 'æð',
    'wrist' : 'úlnlið'
}
