#!/usr/bin/env python
# coding: utf-8

colors = {
    'black' : 'nero',
    'blue' : 'blu',
    'light blue': 'azzurro',
    'navy blue' : 'blu marino',
    'brown' : 'bruno',
    'chestnut brown' : 'marrone',
    'gold' : 'dorato',
    'green' : 'verde',
    'dark green' : 'verde scuro',
    'light green' : 'verde chiaro',
    'gray' : 'grigio',
    'lavender' : 'color lavanda',
    'orange' : 'arancione',
    'pink' : 'rosa',
    'purple' : 'porpora',
    'red' : 'rosso',
    'violet' : 'violetto',
    'white' : 'bianco',
    'yellow' : 'giallo'
}

numbers = {
    '1' : 'uno',
    '2' : 'due',
    '3' : 'tre',
    '4' : 'quattro',
    '5' : 'cinque',
    '6' : 'sei',
    '7' : 'sette',
    '8' : 'otto',
    '9' : 'nove',
    '10' : 'dieci',
    '11' : 'undici',
    '12' : 'dodici',
    '13' : 'tredici',
    '14' : 'quattordici',
    '15' : 'quindici',
    '16' : 'sedici',
    '17' : 'diciassette',
    '18' : 'diciotto',
    '19' : 'diciannove',
    '20' : 'venti',
    '21' : 'ventuno',
    '22' : 'ventidue',
    '23' : 'ventitré',
    '24' : 'ventiquattro',
    '25' : 'venticinque',
    '26' : 'ventisei',
    '27' : 'ventisette',
    '28' : 'ventotto',
    '29' : 'ventinove',
    '30' : 'trenta',
    '40' : 'quaranta',
    '50' : 'cinquanta',
    '60' : 'sessanta',
    '70' : 'settanta',
    '80' : 'ottanta',
    '90' : 'novanta',
    '100': 'cento'
}

body_parts =  {
    'ankle' : 'la caviglia',
    'arm' : 'il braccio',
    'armpit' : 'l\'ascella',
    'artery' : 'l\'arteria',
    'bone' : 'l\'osso',
    'brain' : 'il cervello',
    'calf' : 'il polpaccio',
    'chest' : 'il torace',
    'collarbone' : 'la clavicola',
    'elbow' : 'il gomito',
    'finger' : 'il dito',
    'foot' : 'il piede',
    'hand' : 'la mano',
    'heart' : 'il cuore',
    'heel' : 'il calcagno',
    'hip' : 'l\'anca',
    'index finger' : 'l\'indice',
    'knee' : 'il ginocchio',
    'larynx' : 'la laringe',
    'leg' : 'la gamba',
    'middle finger' : 'il medio',
    'muscle' : 'il muscolo',
    'nail' : 'l\'unghia',
    'nerve' : 'il nerve',
    'pinkie' : 'il mignolo',
    'rib' : 'la costola',
    'ring finger' : 'l\'anulare',
    'shoulder' : 'la spalla',
    'stomach' : 'lo stomaco',
    'thumb' : 'il pollice',
    'vein' : 'la vena',
    'wrist' : 'il polso',


}
